### ISSUE TITLE
/src folder is missing

### ISSUE THREAD

**Issue by eugef** [singingwolfboy/react-mailmerge#8]
Webpack config references the `/src/index.js` but the whole`/src/` folder is missing

**Comment by singingwolfboy** [comment]
That webpack config is run by Apex, in the context of each Lambda function individually. Every Lambda function (in the `/functions` directory) has its own `src/index.js` file. Check out the [structuring projects section of the Apex documentation](http://apex.run/#structuring-projects) for more information.

Does that help make this clearer?

**Comment by eugef** [comment]
Yes, thanks
